name: Assign PR creator
on:
  pull_request:
    types: [ opened ]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}