name: CD - Deploy to S3

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop') &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./build-artifacts s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            --paths "/*"
